#!/usr/bin/bash

# code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension adpyke.codesnap
code --install-extension aki77.html-erb
code --install-extension aliariff.vscode-erb-beautify
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension docker.docker
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension expo.vscode-expo-tools
code --install-extension forevolve.git-extensions-for-vs-code
code --install-extension formulahendry.code-runner
code --install-extension gieson.dupe-file
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension gruntfuggly.todo-tree
code --install-extension hollowtree.vue-snippets
code --install-extension hridoy.rails-snippets
code --install-extension huizhou.githd
code --install-extension jonathanschlitt.open-in-system-terminal
code --install-extension lakshits11.best-themes-redefined
code --install-extension manuelpuyol.erb-linter
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension miguelsolorio.fluent-icons
code --install-extension miguelsolorio.symbols
code --install-extension misogi.ruby-rubocop
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension mtxr.sqltools
code --install-extension naumovs.color-highlight
code --install-extension orta.vscode-jest
code --install-extension qwtel.sqlite-viewer
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shaharkazaz.git-merger
code --install-extension shopify.ruby-lsp
code --install-extension sianglim.slim
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension sonarsource.sonarlint-vscode
code --install-extension stevensona.character-count
code --install-extension tomclose.format-erb
code --install-extension tomoki1207.pdf
code --install-extension tomoki1207.selectline-statusbar
code --install-extension tyriar.sort-lines
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.migrate-java-to-azure
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-java-upgrade
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vue.volar
code --install-extension zneuray.erb-vscode-snippets
